### PR TITLE
cookie support & stuff

### PR DESCRIPTION
**Pull request by igel-kun**
main changes are:
1) cookie support beta - I did some testing and successfully downloaded videos from login-requiring sites
2) the `config` file is automatically detected in `..` if it exists and is passed to `youtube-dl` via `--config-location`
3) some more exception handling which might come in handy if anyone ever has troubles with this script
4) oh this also updates the shebang to `python2`

### CODE REVIEW

**Comment by igel-kun** [comment]
you have no idea how much I hate mozilla `Promise` structures now, almost as much as stripping quotation marks and decoding backslashes in python ^^

**Comment by igel-kun** [comment]
oh this solves #5 and #6  by the way...

**Comment by akhilkedia** [comment]
Thanks for the PR.
I assume it works enough for me to just merge it without testing. (This isn't a mission critical repo after all)
Cheers!

**Comment by igel-kun** [comment]
it would be nice if you could find 5min to update the XPI (if not already done), so people can add it to their firefoxes that aren't developer versions - I don't know, some digital signing seems to be required...

**Comment by akhilkedia** [comment]
I have already, waiting for Mozilla to approve..

**Pull request merged**
